### ISSUE TITLE
[BUG]: Bitcoin chain cannot be signed using the 'signature' function.

### ISSUE THREAD

**Issue by pi-bitstable** [OneKeyHQ/app-monorepo#4332]
![image](https://github.com/OneKeyHQ/app-monorepo/assets/154438863/505ac8a8-3ec8-44ed-af1c-8172487e4d2c)

```tsx
import React from 'react'

export default function Test() {
  async function signMessage() {
    const provider = getProvider()
    if (!provider) return

    try {
      const [account] = await provider.requestAccounts()
      const message = '010203'
      const result = await provider.signMessage(message)
      alert(JSON.stringify([account, result]))
    } catch (error) {
      alert('An error occurred during the signMessage() call.')
    }
  }

  function getProvider() {
    const provider = (window.$onekey && window.$onekey.btc) || window.unisat

    if (!provider) {
      alert('No BTC provider.')
      return undefined
    }
    return provider
  }
  return <button onClick={signMessage}>Test</button>
}

```

- Errror Content
```json
{"name":"Error","message":"Sign message is not supported on hardware.","stack":"Error: Sign message is not supported on hardware.\n    at Object.custom (file:///81172.bundle.js:2:636267)\n    at r.<anonymous> (file:///main.43dd7041.bundle.js:1:28721)\n    at Generator.next (<anonymous>)\n    at n (file:///48751.bundle.js:2:1502161)\n    at s (file:///48751.bundle.js:2:1502364)\n    at file:///48751.bundle.js:2:1502423\n    at new Promise (<anonymous>)\n    at r.<anonymous> (file:///48751.bundle.js:2:1502304)\n    at r.<anonymous> (file:///main.43dd7041.bundle.js:1:29224)\n    at r.<anonymous> (file:///main.43dd7041.bundle.js:1:926)","code":4003}
```

- API Docs 
`https://developer.onekey.so/connect-to-software/webapp-connect-onekey/btc/api-reference/signmessage`

**Comment by originalix** [comment]
Unfortunately, the hardware doesn't currently support psbt signing, but support for this is in the works.

**Comment by pi-bitstable** [comment]
@originalix I think the status shouldn't be closed? Wait for completion before closing.

When can I use the signature feature? Is there an exact time?
Currently, many customers report that it cannot be used normally.

**Comment by pi-bitstable** [comment]
hi, @originalix .
Is there a schedule to fix this issue?
Many users in the community use OneKey to transfer funds. If they cannot sign, they cannot verify that the wallet belongs to the user.

https://docs.unisat.io/dev/unisat-developer-service/unisat-wallet#signmessage

It's just the `signature` message, not `signPsbt`

**Comment by pi-bitstable** [comment]
Has this problem been resolved?

**Comment by ByteZhang1024** [comment]
At present, there is not much effort in this major version, and this issue will be fixed in the next major version.

**Comment by pi-bitstable** [comment]
> 目前这个大版本还没有做太多的努力，这个问题会在下一个大版本中修复。

Is there a date for the next major version?

**Comment by PatrickChoo** [comment]
Hey! BTC signMessage on hardware wallets has been fully supported since v5.17.0. Both ECDSA and BIP322-simple signature types work with hardware devices now.

Please update to the latest version and give it another try. If you run into any issues, feel free to open a new one!
