### ISSUE TITLE
[NEED HELP] TypeError: null is not an object (evaluating 'RNRandomBytes.seed')

### ISSUE THREAD

**Issue by jacko06v** [OneKeyHQ/app-monorepo#655]
i'm trying to use expo go on my iphone but everytime i get 2 errors:
1- `TypeError: null is not an object (evaluating 'RNRandomBytes.seed')`
2- 
```
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and AppRegistry.registerComponent wasn't called.
```

someone know why and how to resolve it?

**full output**

```
iOS Bundling complete 299ms
iOS Running app on iPhone di jacopo

TypeError: null is not an object (evaluating 'RNRandomBytes.seed')
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://172.20.10.2:8081/__generated__/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:1102510:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at /Users/jacopomosconi/Downloads/app-monorepo-1.0.3 2/node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

**Comment by rayston92** [comment]
@loatheb

**Comment by revan-zhang** [comment]
```
Metro (the local dev server) is run from the wrong folder
```
@jacko06v
Which command did you run? If you want to run on the real machine, you need an IOS developer account and the corresponding configuration. After configuring your own developer account and certificate, you need to run `expo run:ios --device` in `packages/app`

**Comment by rayston92** [comment]
@loatheb we should also clarify these on readme file.

**Comment by jacko06v** [comment]
@loatheb I have an IOS developer account, initially I started the app in a simulator, the app opened, it asked me to select a client, but once the client was selected it crashed.
I had read somewhere that until the last commit the app did not go on the simulator, although I downloaded all the updated repo I thought it could be the same error, so I connected my iphone via usb and I ran `expo run: ios --device`

the application has been installed correctly, but as on the simulator, the app opens, when I choose the client it crashes

the problem is that the console does not print any errors!
every time the app crashes the console just prints "iOS Bundling complete"
<img width="596" alt="Schermata 2022-05-08 alle 20 34 52" src="https://user-images.githubusercontent.com/76396947/167310485-d085e38b-1f8d-401c-827e-3d49267595b4.png">

so i started a new client on port 8082, and i tried to connect to it again
now it crashes, but the console prints the error:

```
None of these files exist:
  * App(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * App/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  1 | import registerRootComponent from 'expo/build/launch/registerRootComponent';
  2 |
> 3 | import App from '../../App';
    |                  ^
  4 |
  5 | registerRootComponent(App);
  6 |
Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: slug - 'slug' should match pattern "^[a-zA-Z0-9_\-]+$".
Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: slug - 'slug' should match pattern "^[a-zA-Z0-9_\-]+$".
 ```

**Comment by jacko06v** [comment]
**UPDATE**

After this commit https://github.com/OneKeyHQ/app-monorepo/commit/74700d8a9987f4fa4c354450f6e01795e6ee496c
the app started working on both the simulator and the device!
